# Generated by Django 5.1.7 on 2025-03-19 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="date_recorded",
            field=models.DateField(verbose_name="Дата записи"),
        ),
        migrations.AlterField(
            model_name="grade",
            name="score",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Оценка"
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.student",
                verbose_name="Студент",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.teacher",
                verbose_name="Учитель",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(verbose_name="Дата зачисления"),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=30, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=30, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(max_length=10, verbose_name="Код"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="first_name",
            field=models.CharField(max_length=30, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="last_name",
            field=models.CharField(max_length=30, verbose_name="Фамилия"),
        ),
    ]
